title: How to Handle an Unresponsive SME
description: A quick guide on how to build friendly professional relationships between a technical writer and an SME.
theme: just-the-docs

url: https://IzatheWriter.github.io/HowToHandleAnUnresponsiveSME

aux_links:
  Template Repository: https://github.com/IzatheWriter/HowToHandleAnUnresponsiveSME
